# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: localhost (MySQL 5.5.29)
# Database: filmbox
# Generation Time: 2014-07-20 03:46:52 +0200
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table directors
# ------------------------------------------------------------

DROP TABLE IF EXISTS `directors`;

CREATE TABLE `directors` (
  `id_director` int(3) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `bio` text,
  PRIMARY KEY (`id_director`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `directors` WRITE;
/*!40000 ALTER TABLE `directors` DISABLE KEYS */;

INSERT INTO `directors` (`id_director`, `name`, `country`, `bio`)
VALUES
	(1,'Renny Harlin','March 15, 1959 in Riihimäki, Finland','Born in 15 March 1959 as Renny Lauri Mauritz Harjola, he is the most successful Finnish film director in the history of Hollywood. Harlin started his career in film business in the beginning of 1980s when he was directing commercials and company films for companies like Shell. Later he worked as a buyer for Finnish film distributor and met Finnish ...'),
	(2,'Roger Donaldson','November 15, 1945 in Ballarat, Australia','Roger Donaldson was born on November 15, 1945 in Ballarat, Australia. He is a director and producer, known for The bank job: El robo del siglo (2008), La prueba (2003) and Burt Munro. Un sueño, una leyenda (2005).'),
	(3,'Mimi Leder','January 26, 1952 in New York City, New York, USA','Mimi Leder was born on January 26, 1952 in New York City, New York, USA as Miriam Leder. She is a producer and director, known for Deep Impact (1998), Cadena de favores (2000) and El pacificador (1997). She is married to Gary Werntz. They have one child.'),
	(4,'Christophe Gans','March 11, 1960 in Antibes, Alpes-Maritimes, France','Born in 1960 in Antibes (in the South of France), Christophe Gans became crazy about movies at an early stage. As a teenager, he made a lot of samurai and kung fu super-8 films with his friends. At the end of the seventies, he founded the fanzine \"Rhesus Zero\" about B-movies. In 1980, he studied at the French cinema school Idhec and directed a ...'),
	(5,'Eric Leighton (I)','November 6, 1962 in San Diego, California, USA','Eric Leighton was born on November 6, 1962 in San Diego, California, USA. He is known for his work on Pesadilla antes de Navidad (1993), King Kong (2005) and Los mundos de Coraline (2009).'),
	(6,'Rob L. Cohen','',''),
	(7,'Bruce William Paltrow','November 26, 1943 in Brooklyn, New York City, New York, USA','Bruce Paltrow was born on November 26, 1943 in Brooklyn, New York City, New York, USA as Bruce William Paltrow. He was a writer and producer, known for The White Shadow (1978), A dúo (2000) and St. Elsewhere (1982). He was married to Blythe Danner. He died on October 3, 2002 in Rome, Lazio, Italy.'),
	(8,'David Lynch (I)','January 20, 1946 in Missoula, Montana, USA','Born in precisely the kind of small-town American setting so familiar from his films, David Lynch spent his childhood being shunted from one state to another as his research scientist father kept getting relocated. He attended various art schools, married Peggy Lynch and then fathered future director Jennifer Chambers Lynch shortly after he turned...'),
	(9,'Shekhar Kapur','December 6, 1945 in Lahore, Punjab, British India [now Pakistan]','Shekhar Kapur was born on December 6, 1945 in Lahore, Punjab, British India [now Pakistan]. He is an actor and director, known for Elizabeth (1998), Elizabeth: La edad de oro (2007) and New York, I Love You (2008). He was previously married to Suchitra Krishnamoorthi.'),
	(10,'James Wong (IV)','','James Wong is a producer and writer, known for Destino final (2000), Destino final 3 (2006) and El único (2001). He is married to Teena Wong. They have three children.'),
	(11,'Kenneth Branagh','December 10, 1960 in Belfast, Northern Ireland, UK','Kenneth Charles Branagh was born on December 10, 1960, in Belfast, Northern Ireland, UK, to parents William Branagh, a carpenter born in 1930, and Frances Branagh, also born in 1930. His brother, William Branagh Jr., was born in 1955 and sister, Joyce Branagh, was born in 1970. At 23, Branagh joined the Royal Shakespeare Company, where he took on ...');

/*!40000 ALTER TABLE `directors` ENABLE KEYS */;
UNLOCK TABLES;


# Dump of table film
# ------------------------------------------------------------

DROP TABLE IF EXISTS `film`;

CREATE TABLE `film` (
  `id_film` int(3) unsigned NOT NULL AUTO_INCREMENT,
  `id_director` int(3) unsigned DEFAULT NULL,
  `title` varchar(51) NOT NULL,
  `genre` varchar(50) DEFAULT NULL,
  `language` varchar(50) DEFAULT NULL,
  `time` decimal(4,2) DEFAULT NULL,
  `description` varchar(961) DEFAULT NULL,
  `cover` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_film`),
  KEY `FK_film_directors` (`id_director`),
  CONSTRAINT `FK_film_directors` FOREIGN KEY (`id_director`) REFERENCES `directors` (`id_director`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `film` WRITE;
/*!40000 ALTER TABLE `film` DISABLE KEYS */;

INSERT INTO `film` (`id_film`, `id_director`, `title`, `genre`, `language`, `time`, `description`, `cover`)
VALUES
	(1,1,'Deep Blue Sea','Action / Horror / Thriller','English',0.00,'Searching for a cure to Alzheimer\'s disease a group of scientists on an isolated research facility become the bait as a trio of intelligent sharks fight back.','css/pictures/1_cover.jpg'),
	(2,2,'Dante\'s Peak','Action / Adventure / Drama','English',0.00,'Volcanologist Harry Dalton and mayor Rachel Wando of Dante\'s Peak try to convince the city council and the other volcanologists that the volcano right above Dante\'s peak is indeed dangerous. People\'s safety is being set against economical interests',''),
	(3,3,'Deep Impact','Drama / Sci-Fi / Thriller','English',2.00,'Unless a comet can be destroyed before colliding with Earth, only those allowed into shelters will survive. Which people will survive?',''),
	(4,4,'Crying Freeman','Action / Crime / Thriller','English / Japanese',2.00,'A lethal assassin for a secret Chinese organisation, who sheds tears of regret each time he kills, is seen swiftly and mercilessly executing three Yakuza gangsters by a beautiful artist. She is captivated by the grace of his kill and later falls in love w',''),
	(5,5,'Dinosaur','Animation / Action / Adventure / Family / Thriller','English',1.36,'Dinosaur is set in the twilight of the dinosaurs, when the killer comet arrives, and deals with the legacy they leave for the emerging mammals. One dinosaur who had been raised by Lemurs becomes a sort of saurian Moses and leads the Lemurs to safety after',''),
	(6,6,'Dragon: The Bruce Lee Story','Action / Biography / Drama','English',2.00,'True story of the kung-fu king Bruce Lee that dwell not on his mysterious death but his inspirational life and improable rise to stardom from the streets of Hong Kong',''),
	(7,7,'Duets','Comedy / Drama / Music','English',0.00,'Duets is a road-trip comedy which revolves around the little known world of karaoke and the whimsical characters who inhabit it. There\'s the struggling singer who dreams of making it to the big time, a frustrated salesman who ends up on an unexpected road',''),
	(8,8,'Dune','Action / Adventure / Sci-Fi / Fantasy','English',2.28,'A spectacular journey through the wonders of space and the mysteries of time, from the boundaries of the incredible to the borders of the impossible',''),
	(9,9,'Elizabeth','Biography / Drama / History','English / French',2.06,'A film of the early years of the reign of Elizabeth I of England and her difficult task of learning what is necessary to be a monarch',''),
	(10,10,'Final Destination','Horror / Thriller / Mystery / Fantasy','English / French',0.00,'After having a vision of his friends crashing in a plane, he tells them not to get on only later his friends start getting killed one by one',''),
	(11,11,'Frankenstein','Drama / Horror / Fantasy / Sci-Fi','English',2.05,'Based on Mary Shelly\'s novel. Frankenstein tells the story of Victor Frankenstein(Kenneth Brannagh). A promising young doctor who devestated by the death of his mother during child birth, becomes obsessed with bringing the dead back to life. His experimen',''),
	(12,NULL,'Godzilla','Action / Sci-Fi / Thriller','English / French / Japanese',2.31,'Following the French atomic bomb tests in the South Pacific, an unknown creature is spotted passing eastward through the Panama Canal. Scientist Niko Tatopolous is called in to investigate the matter, and he quickly arrives at the conclusion that a giant,',''),
	(13,NULL,'The Haunting','Horror / Thriller / Mystery','English',0.00,'When Eleanor, Theo, and Luke decide to take part in a sleep study at a huge mansion they get more than they bargained for when Dr. Marrow tells them of the house\'s ghostly past',''),
	(14,NULL,'The Ten Commandments','Drama','English',0.00,'The Egyptian Prince, Moses, learns of his true heritage as a Hebrew and his divine mission as the deliverer of his people',''),
	(15,NULL,'Les rivières pourpres II - Les anges de l\'apocalyps','Thriller / Action / Crime','French / German /Italian',0.00,'Chief Niemans is investigating a series of ritual murders: The victims are crucified. He teams up with young officer Reda, who gets embroiled after a man dressed as a monk tries to kill a confused guy Reda picked up on the street. Together with a speciali',''),
	(16,NULL,'Sneakers','Drama','English / French',0.00,'The tumultuous political landscape of Paris in 1968 serves as the backdrop for a tale about three young cineastes who are drawn together through their passion for film. Matthew, an American exchange student, pursuing his education abroad in Paris, becomes',''),
	(17,NULL,'The 13th Warrior','Action / Adventure / Fantasy','English / Latin',0.00,'In AD 922, Arab courtier Ahmad Ibn Fadlan accompanies a party of Vikings to the barbaric North. Ibn Fadlan is appalled by the Vikings customs-- their wanton sexuality, their disregard for cleanliness, their cold-blooded human sacrifices. And then he learn',''),
	(18,NULL,'The Bone Collector','Drama / Mystery / Thriller','English',0.00,'Two cops on the trail of a brutal killer. They must see as one, they must act as one, they must think as one, before the next victim falls',''),
	(19,NULL,'Gladiator','Action / Adventure / Drama','English',2.59,'Maximus is a powerful Roman general, loved by the people and the aging Emperor, Marcus Aurelius. Before his death, the Emperor chooses Maximus to be his heir over his own son, Commodus, and a power struggle leaves Maximus and his family condemned to death',''),
	(20,NULL,'The Green Mile','Crime / Drama / Fantasy / Mystery','English / French',3.14,'The story about the lives of guards on death row leading up to the execution of a wrongly accused man who has the power of faith healing',''),
	(21,NULL,'The World Is Not Enough','Action / Adventure / Thriller','English / Russian',2.14,'James Bond uncovers a nuclear plot when he protects an oil heiress from her former kidnapper, an international terrorist who can\'t feel pain',''),
	(22,NULL,'The Patriot','Action / Drama / War','English',0.00,'After proving himself on the field of battle in the French and Indian War, Benjamin Martin wants nothing more to do with such things, preferring the simple life of a farmer. But when his son Gabriel enlists in the army to defend their new nation, America,',''),
	(23,NULL,'First Knight','Adventure / Drama / Romance','English',2.24,'Lancelot falls in love with Guinevere, who is due to be married to King Arthur. Meanwhile, a violent warlord tries to seize power from Arthur and his Knights of the Round Table',''),
	(24,NULL,'The Pelican Brief','Thriller / Drama / Mystery','English',2.35,'Two Supreme Court Justices have been assassinated. One lone law student has stumbled upon the truth. An investigative journalist wants her story. Everybody else wants her dead',''),
	(25,NULL,'The Talented Mr. Ripley','Crime / Drama / Thriller','English / Italian',2.31,'In late 1950\'s New York, Tom Ripley, a young underachiever, is sent to Europe to retrieve a rich and spoiled millionaire playboy, named Dickie Greenleaf. But when the errand fails, Ripley kills the playboy and begins to assume his life',''),
	(26,NULL,'The Cable Guy','Comedy / Drama / Thriller','English / French',0.00,'A lonely and disturbed cable guy raised on television just wants a new friend, but his target, a designer, rejects him, with bad consequences',''),
	(27,NULL,'Fiddler on the Roof','Drama / Family / Musical','English / Hebrew',3.01,'In pre-revolutionary Russia, a poor Jewish peasant must contend with marrying off his three daughters while antisemitic sentiment threatens his home',''),
	(28,NULL,'The Outlaw Josey Wales','Action / Drama / Western','English',2.25,'Josey Wales makes his way west after the Civil War, determined to live a useful and helpful life. He joins up with a group of settlers who need the protection that a man as tough and experienced as he is can provide. Unfortunately, the past has a way of c',''),
	(29,NULL,'The Thirteenth Floor','Mystery / Romance / Sci-Fi / Thriller','English',0.00,'Computer scientist Hannon Fuller has discovered something extremely important. He\'s about to tell the discovery to his colleague, Douglas Hall, but knowing someone is after him, the old man leaves a letter in his computer generated parallel world that\'s j',''),
	(30,NULL,'The Insider','Biography / Drama / History / Thriller','English / Japanese / Arabic',0.00,'A research chemist comes under personal and professional attack when he decides to appear in a \"60 Minutes\" expose on Big Tobacco',''),
	(31,NULL,'Instinct','Drama / Thriller','English',2.10,'When a noted anthropologist who left society to live in the jungle is imprisoned for murder, it\'s up to young psychologist to get through to him',''),
	(32,NULL,'Interview with the Vampire: The Vampire Chronicles','Drama / Horror / Fantasy','English',2.05,'In 1791, plantation owner Louis outside New Orleans has lost his courage to live. He gets bitten by the vampire Lestat and is himself turned into one. He hates being a vampire and refuses to kill humans. Louis and Lestat turn a little girl, Claudia, into ',''),
	(33,NULL,'Jade','Action / Crime / Thriller / Drama','English',1.59,'Someone does a nasty hatchet job on a San Fransisco big noise and the Assistant D.A. takes charge of the investigation. Through a web of blackmail and prostitution involving the Governor, an old lover of the law man emerges as a prime suspect and he has t',''),
	(34,NULL,'Jesus','Drama','English',4.00,'A movie about the life, work and death of Jesus as we know it from the Bible',''),
	(35,NULL,'The Devil\'s Advocate','Drama / Mystery / Thriller','English / German / Italian / Mandarin',2.40,'Based on a book by Andrew Neiderman, the film centers on a young lawyer who joins a New York firm only to discover that his boss has an increasingly bizarre personality',''),
	(36,NULL,'Apt Pupil','Drama / Thriller','English',0.00,'Neighborhood boy Todd Bowden (Renfro) discovers that an old man living on his block named Arthur Denker (Mackellan) is nazi war criminal. Bowden confronts Denker and offers him a deal: Bowden will not go to the authorities if Denker tells him stories of t',''),
	(37,NULL,'Eraser','Action / Drama / Thriller','English',0.00,'John Kruger is a U.S. marshal who is assigned to protect Lee Cullen, who works for the Cyrez Corporation, a company that manufactures top secret weapons for the military. Lee knows about a scam going on within Cyrez Corporation, and the man behind it is d',''),
	(38,NULL,'Bicentennial Man','Sci-Fi / Drama / Romance','English',2.20,'This film follows the \'life\' and times of the lead character, an android (Robin Williams) who is purchased as a household robot programmed to perform menial tasks. Within a few days the Martin family realizes that they don\'t have an ordinary droid as Andr',''),
	(39,NULL,'The Devil\'s Own','Action / Drama / Thriller','English',0.00,'One of top Northern Ireland IRA terrorists, Frankie McGuire, escapes to NY, where he, under the name of Rory Devaney, with support of friendly judge Peter Fitzsimmons, lives in the house of Irish cop Tom O\'Meara, who doesn\'t know who Frankie really is. Ro',''),
	(40,NULL,'Seven Years in Tibet','Adventure / Biography / Drama','English / German / Mandarin / Tibetan',2.31,'True story of Heinrich Harrer, an Austrian mountain climber who became friends with the Dalai Lama at the time of China\'s takeover of Tibet',''),
	(41,NULL,'8MM','Drama / Mystery / Thriller','English',2.05,'Tom Welles, private eye, is hired by a wealthy widow, whose well-known husband passed away recently. She has found a reel of S8-film in a safe. On the film is a cruel slaughtering of a young girl, who obviously does not pretend or act: A snuff-movie. Well',''),
	(42,NULL,'Aliens','Horror / Sci-Fi / Thriller','English',0.00,'On what should have been a trip back to Earth, the Nostromo, a mining freighter, is automatically re-routed to a desolate planet after receiving an SOS coming from it. After the crew is awakened, they investigate the source of the SOS, and discover a dere',''),
	(43,NULL,'Amadeus','Drama / Music','English / Italian / German',0.00,'The incredible story of Wolfgang Amadeus Mozart, told in flashback mode by Antonio Salieri - now confined to an insane asylum',''),
	(44,NULL,'Amistad','Drama / History / Mystery','English / Mende / Spanish',2.54,'AMISTAD is about a 1839 mutiny aboard a slave ship that is traveling towards the Northeast Coast of America. Much of the story involves a court-room drama about the free-man who led the revolt',''),
	(45,NULL,'Anaconda','Thriller / Horror / Adventure / Action','English',2.15,'A \"National Geographic\" crew heads down the Amazon in a jungle boat to make a documentary on a long-lost tribe of natives. En route, they rescue a hunter from his sinking boat and take him on board. After the ship\'s captain is attacked by a poisonous inse',''),
	(46,NULL,'Anna and the King','Drama / History / Romance','English / Thai / French',1.48,'The story of the romance between the King of Siam and the widowed British schoolteacher Anna Leonowens during the 1860\'s',''),
	(47,NULL,'Armageddon','Action / Drama / Romance / Sci-Fi / Thriller','English / Russian',1.50,'A giant, global-killing asteriod, like the one that killed off the dinosaurs 65 million years ago is 18 days away from hitting the Earth. NASA\'s been caught with their pants down and needs a new plan to stop the rock. They enlist the help of Harry Stamper',''),
	(48,NULL,'Autumn in New York','Romance / Drama','English',0.00,'Romantic drama about an aging playboy who falls for a sweet, but terminally ill, young woman',''),
	(49,NULL,'Bad Boys','Action / Comedy / Crime / Thriller','English',0.00,'Marcus Burnett is a hen-pecked family man. Mike Lowry is a foot-loose and fancy free ladies\' man. Both are Miami policemen, and both have 72 hours to reclaim a consignment of drugs stolen from under their station\'s nose. To complicate matters, in order to',''),
	(50,NULL,'Bats','Thriller / Horror','English',2.18,'Bats, the result of a government experiment gone wrong, have suddenly become intelligent, vicious, and omnivorous, and are attacking people near Gallup, Texas. Bat specialist Sheila Casper and her assistant Jimmy are brought in but can they stop the bats ',''),
	(51,NULL,'Big Daddy','Comedy / Drama','English / Italian',2.21,'A lazy law school grad adopts a kid to impress his girlfriend, but everything doesn\'t go as planned and he becomes the unlikely foster father',''),
	(52,NULL,'Blade Runner','Action / Drama / Sci-Fi / Thriller','English / German / Cantonese / Japanese',0.00,'Deckard, a blade runner, has to track down and terminate 4 replicants who hijacked a ship in space and have returned to earth seeking their maker...',''),
	(53,NULL,'Leggenda del pianista sull\'oceano, La','Drama / Fantasy / Music','English / French',0.00,'Shortly after the Second World War, Max, a transplanted American, visits an English pawn shop to sell his trumpet...',''),
	(54,NULL,'The Horse Whisperer','Drama / Romance','English',2.50,'A teenage girl riding a horse is hit by a truck. To help heal her troubled/injured daughter, and horse, the mother takes them to Montana to recuperate at the ranch of a Â´horse whispererÂª, a horse healer of mystical talents. The mother proceeds to fall in love with him, as well',''),
	(55,NULL,'The Scarlet Letter','Drama / Romance','English',2.25,'In 1666 in the Massachusetts Bay colony, Puritans and Algonquian have an uneasy truce. Hester arrives from England, seeking independence. Awaiting her husband, she establishes independence, fixing up a house, befriending Quakers and other outsiders. Passion draws her to a young pastor. He feels the same; when they learn her husband has probably died at the hands of Indians, they consummate their love. A child is born, and on the day Hester is publicly humiliated and made to wear a scarlet letter, her husband appears after a year with Indians. Calling himself Chillingworth, he seeks revenge, searching out HesterÂªs lover and stirring fears of witchcraft. Will his murderous plot succeed?',''),
	(56,NULL,'The Mask of Zorro','Action / Adventure / Comedy / Romance / Western','English',2.25,'Don Diego de la Vega/Zorro returns from exile to avenge the death of his wife, who was killed by his enemy, Don Rafael Montero. Montero took de la VegaÂªs daughter, Elena, and raised her as Elena Montero. The older Zorro takes it upon himself to train his successor, Alejandro Murrieta, who had once helped Zorro escape. Alejandro is cocky and comical, but shows some talent with sword play. What happens when the daughter and the protÃˆgÃˆ of Zorro meet? Sparks!',''),
	(57,NULL,'The Man in the Iron Mask','Action / Adventure / Drama','English',2.15,'Paris is starving, but the King of France is more interested in money and bedding women. When a young soldier dies for the sake of a shag, Aramis, Athos and Porthos band together with a plan to replace the king. Unknown to many, there is a 2nd king, a twin, hidden at birth, then imprisoned for 6 years behind an iron mask. All that remains now is DÂªArtagnan, will he stand against his long time friends, or do what is best for his country?',''),
	(58,NULL,'The Mummy','Action / Adventure / Comedy / Fantasy / Horror / T','English / Arabic',2.04,'An English librarian called Evelyn Carnahan (Weisz) becomes interested in starting an archaeological dig at the ancient city of Hamunaptra. He gains the help of Rick OÂªConnell (Fraser), after saving him from his death. What Evelyn, her brother Jonathan (Hannah) and Rick is unaware of if that another group of explorers are interested in the same dig. Unfortunatly for everyone, this group ends up unveiling a curse which has risen the dead High Priest Imhotep (Vosloo). Now Â´The MummyÂª is awake and itÂªs going to take a lot more than guns to send him back from where he came from',''),
	(59,NULL,'The Perfect Storm','Adventure / Drama / Action / Thriller','English',2.15,'In October 1991, a confluence of weather conditions combined to form a killer storm in the North Atlantic. Caught in the storm was the sword-fishing boat Andrea Gail. Magnificent foreshadowing and anticipation fill this true-life drama while minute details of the fishing boats, their gear and the weather are juxtaposed with the sea adventure',''),
	(60,NULL,'Lost in Space','Action / Adventure / Sci-Fi','English',2.15,'The Robinson family was going into space to fight for a chance for humanity. Now they are fighting to live long enough to find a way home',''),
	(61,NULL,'Mission Impossible II','Action / Adventure / Thriller','English',2.05,'A secret agent is sent to Sydney, to find and destroy a genetically modified disease called Â´ChimeraÂª',''),
	(62,NULL,'Magnolia','Drama','German / English / French',3.10,'An epic mosaic of several interrelated characters in search of happiness, forgiveness, and meaning in the San Fernando Valley',''),
	(63,NULL,'The Matrix','Action / Thriller / Sci-Fi','English',2.15,'In the near future, a computer hacker named Neo (Keanu Reeves) discovers that all life on Earth may be nothing more than an elaborate facade created by a malevolent cyber-intelligence, for the purpose of placating us while our life essence is Â´farmedÂª to fuel the MatrixÂªs campaign of domination in the Â´realÂª world. He joins like-minded Rebel warriors Morpheus (Laurence Fishburne) and Trinity (Carrie Ann Moss) in their struggle to overthrow the Matrix',''),
	(64,NULL,'New Jack City','Crime / Drama / Thriller','English',1.37,'A crime lord ascends to power and becomes megamanical while a maverick police detective vows to stop him',''),
	(65,NULL,'Out of Sight','Comedy / Crime / Romance / Thriller','English',2.05,'A career bank robber breaks out of jail and shares a moment of mutual attraction with a US Marshall he has kidnapped',''),
	(66,NULL,'Patch Adams','Comedy / Drama','English',2.00,'Robin Williams stars as Patch Adams, in this true story of a heroic man, determined to become a medical doctor because he enjoys helping people. Unfortunately, the medical and scientific community does not appreciate his methods of healing the sick, while the actual patients, medical professors, and hospital nurses all appreciate the work *he* can do, because they are unable to do it',''),
	(67,NULL,'Phenomenon','Drama / Romance / Fantasy','English',2.05,'An ordinary man sees a bright light descend from the sky, and discovers he now has super-intelligence and telekinesis',''),
	(68,NULL,'Point Break','Action / Adventure / Crime / Drama / Sport / Thril','English',2.00,'In the coastal town of Los Angeles, a gang of bank robbers call themselves the ex-presidents. commit their crimes while wearing masks of ex-presidents Reagan, Carter, Nixon and Johnson. The F.B.I. believes that the members of the gang could be surfers and send young agent Johnny Utah undercover at the beach to mix with the surfers and gather information. Utah meets surfer Bodhi and gets drawn into the lifestyle of his new friend',''),
	(69,NULL,'Sense and Sensibility','Drama / Comedy / Romance','English / French',2.15,'Rich Mr. Dashwood dies, leaving his second wife and her daughters poor by the rules of inheritance. Two daughters are the titular opposites',''),
	(70,NULL,'Chain Reaction','Action / Thriller / Drama','English',1.40,'Two researchers in a green alternative energy project are put on the run when they are framed for murder and treason',''),
	(71,NULL,'Romeo + Juliet','Crime / Drama / Romance','English',2.00,'ShakespeareÂªs famous play is updated to the hip modern suburb of Verona still retaining its original dialogue',''),
	(72,NULL,'Sleepers','Crime / Drama / Thriller','English',2.30,'After a prank goes disastrously wrong, a group of boys are sent to a detention center where they are brutalized; over 10 years later, they get their chance for revenge',''),
	(73,NULL,'I Dreamed of Africa','Drama','English',2.00,'Kuki, a divorced Italian socialite, changes her life after a serious car crash. She accepts a marriage proposal from Paolo Gallmann, a man she doesn\'t know well, and she moves to Kenya with him and her young son to start a cattle ranch. Challenges beset her, not the least of which is Paulo\'s love of danger and his leaving for days on end to hunt and fish with pals. She must face fierce storms, roving lions, venomous snakes, and murderous poachers, and she must find accommodation with a neighboring tribe. Her mother entreats her to return home. Can Kuki live her dream, tame Paolo, guide her son safely past the perils and errors of youth, and serve Africa?',''),
	(74,NULL,'Stigmata','Fantasy / Mystery / Drama / Horror / Thriller','Assyrian Neo-Aramaic / English / Portuguese / Ital',1.45,'A priest from the Vatican is sent in to investigate claims that a small town in Brazil has a church where statues bleed from the eyes. Meanwhile, a young woman in the U.S. begins to show signs of stigmata, the wounds of Christ. The priest from the Vatican links up with her and cares for her as she is increasingly afflicted by the stigmata. Her ranting and raving finally begins to make sense to the priest who starts to question what his religion has stood for for the last 1900 years',''),
	(75,NULL,'Supernova','Sci-Fi / Thriller','English',1.31,'Set in the 22nd century, when a battered salvage ship sends out a distress signal, the seasoned crew of the rescue hospital ship Nova-17 responds. What they find is a black hole--that threatens to destroy both ships--and a mysterious survivor whose body quickly mutates into a monstrous and deadly form',''),
	(76,NULL,'Terminator 2: Judgment Day','Action / Sci-Fi / Thriller','English / Spanish',2.20,'Nearly 10 years have passed since Sarah Connor was targeted for termination by a cyborg from the future. Now her son, John, the future leader of the resistance, is the target for a newer, more deadly terminator. Once again, the resistance has managed to send a protector back to attempt to save John and his mother Sarah',''),
	(77,NULL,'The Arrival','Sci-Fi / Thriller / Mystery / Action','English',2.00,'Zane Ziminski is an astrophysicist who receives a message that seems to have extraterrestrial origins. Eerily soon after his discovery, Zane is fired. He then embarks on a search to determine the origins of the transmission that leads him into a Hitchcockian labyrinth of paranoia and intrigue',''),
	(78,NULL,'The Avengers','Action / Adventure','English',1.40,'British Ministry agent John Steed, under direction from \"Mother\", investigates a diabolical plot by arch-villain Sir August de Wynter to rule the world with his weather control machine. Steed investigates the beautiful Doctor Mrs. Emma Peel, the only suspect, but simultaneously falls for her and joins forces with her to combat Sir August',''),
	(79,NULL,'The Beach','Drama / Adventure / Thriller','English / French / Swedish / Thai / Serbo-Croatian',2.00,'Garland\'s novel centers on a young nicotine-addicted traveler named Richard, an avid pop-culture buff with a particular love for video games and Vietnam War movies. While at a hotel in Bangkok, he finds a map left by his strange, whacked-out neighbor, who just committed suicide. The map supposedly leads to a legendary island paradise where some other wayward souls have settled',''),
	(80,NULL,'The Cell','Crime / Drama / Fantasy / Horror / Sci-Fi / Thrill','English',1.47,'Catharine Deane is a psychotherapist who is part of a revolutionary new treatment which allows her mind to literally enter the mind of her patients. Her experience in this method takes an unexpected turn when an FBI agent comes to ask for a desperate favour. They had just tracked down a notorious serial killer, Carl Stargher, whose MO is to abduct women one at a time and place them in a secret area where they are kept for about 40 hours until they are slowly drowned. Unfortunately, the killer has fallen into an irreversible coma which means he cannot confess where he has taken his latest victim before she dies. Now, Catherine Deane must race against time to explore the twisted mind of the killer to get the information she needs, but Stargher\'s damaged personality poses dangers that threaten to overwhelm her',''),
	(81,NULL,'The Miracle Maker','Animation / Biography / Drama','English',1.31,'The story of Jesus Christ',''),
	(82,NULL,'The Sixth Sense','Drama / Mystery / Thriller','English / Latin / Spanish',1.47,'True story of Heinrich Harrer, an Austrian mountain climber who became friends with the Dalai Lama at the time of China\'s takeover of Tibet',''),
	(83,NULL,'The Skulls','Action / Crime / Drama / Thriller','English',1.45,'Luke McNamara, a college senior from a working class background joins a secret elitist college fraternity organization called \"The Skulls\", in hope of gaining acceptance into Harvard Law School. At first seduced by the club\'s trapping of power and wealth, a series of disturbing incidents, such as his best friends suicide, leads Luke to investigate the true nature of the organization and the truth behind his friends supposed suicide. He starts realizing that his future and possibly his life is in danger',''),
	(84,NULL,'The Watcher','Crime / Mystery / Thriller','English',1.37,'David Allen Griffin is a cool killer- time and time again, he chooses a female victim, studies her for weeks till he knows her routine to the smallest detail, makes meticulous preparations using his forensic knowledge to gain entry when she\'s quite alone, subdues her and administers a long, torturous death. Joel Campbell got so frustrated by his failure to capture Griffin in LA that he quit the FBI, moved to Chicago and remains in psychiatric therapy, unable to function normally. Then he realizes, when opening his mail very late, that a new murder victim is Griffin\'s, and the killer send him pictures of her. Campbell reports this to the police, but is unwilling to join them in the search, suggesting Griffin is too slick and clever; yet he won\'t get out of it that easily...',''),
	(85,NULL,'Three Kings','Action / Adventure / Comedy / Drama / History / Wa','English / Arabic',1.45,'A small group of adventurous American soldiers in Iraq at the end of the Gulf War are determined to steal a huge cache of gold reputed to be hidden somewhere near their desert base. Finding a map they believe will take them to the gold, they embark on a journey that leads to unexpected discoveries, enabling them to rise to a heroic challenge that drastically changes their lives',''),
	(86,NULL,'Titan A.E.','Animation / Action / Sci-Fi / Adventure','English',1.34,'One thousand years from now, aliens destroy Earth in fear of the Titan project. Some humans escape, becoming a downtrodden Diaspora, living in impoverished settlements. The mysterious Titan spacecraft also escapes, and its inventor has hidden it before dying. A spacecraft captain and its pilot, Korso and Akima, two humans, seek out Cale, the youthful son of the dead scientist and explain that he must help them find the Titan, which holds a mechanism to unite and save humanity. Cale refuses, but the arrival of the killer aliens persuades him to join Korso. Can he avoid his pursuers, know friend from foe, find the Titan, and embrace his humanity, a nature he has despised until now?',''),
	(87,NULL,'Titus','Drama / Fantasy / Horror / War','English / Latin',2.42,'This film is an adaptation of the Shakespeare play \"Titus Andronicus.\" Titus returns victorious from war, only to plant the seeds of future turmoil for himself and his family. Who says revenge is sweet?',''),
	(88,NULL,'Turbulence','Drama / Fantasy / Horror / War','English',1.40,'Ryan Weaver romances beautiful women before he kills them. Ryan is arrested, convicted, and is part of a Christmas Eve transfer of prisoners on a transcontinental 747 commercial flight. Other airlines at JFK may have holiday passengers waiting on stand-by, but this jumbo jet takes off with a lot of empty seats. Ryan and another prisoner overpower and kill their guards. The few civilian passengers are herded into a \"pantry\" on the plane and are not seen again until the end of the movie. Ryan eliminates the other prisoners and all the crew members except Teri Halloran. The remainder of the movie follows a \"cat-and-mouse\" game between Ryan and Teri on the 747',''),
	(89,NULL,'The Last Marshal','Action / Thriller','English',1.42,'Marshall McClary, one of the most violent, racist, foul- mouthed Marshalls in Texas, is in the middle of resolving a hostage situation (by shooting everyone he sees) when the FBI agents show up, interfering with his negotiation, and ending the event with McClary being wounded and two of the criminals escaping. After hearing that the two fugitives has fled to Miami, McClary follows behind them, working with the local police and offending every single person he encounters',''),
	(90,NULL,'Ordinary Madness','Thriller','English / Italian',1.30,'Writer-Director Bernardo Gigliotti\'s Ordinary Madness is a Hitchcock-like thriller set in Los Angeles...',''),
	(91,NULL,'Universal Soldier','Action / Drama / Sci-Fi','English',1.43,'Luc and Scott were killed in Vietnam, but the army has a secret project for reanimating dead people as near-perfect soldiers.',''),
	(92,NULL,'Urban Legend','Horror / Thriller / Mystery','English',1.40,'There\'s a campus killer on the loose who\'s making urban legends, like the one about eating pop rocks and soda at the same time will make your stomach explode and the one about a psycho with an axe stepping into the backseat of your car at the gas station when not looking, into reality',''),
	(93,NULL,'Meet Joe Black','Fantasy / Mystery / Romance / Drama','English',1.58,'Joe Black and Bill Parrish enter into a most unusual gentleman\'s agreement. Wealthy media tycoon William Parrish leads a charmed existence until Death comes calling with an extraordinary proposition - he\'ll delay Bill\'s imminent demise in exchange for a tour of life. Innocent, enigmatic and often hilarious, Joe disrupts Bill\'s world of privilege and corporate intrigue. But when he falls for Bill\'s beautiful daughter, Joe threatens to change the rules. Now Bill must fight not for his future, but for those he loves in this bittersweet tale of life and death',''),
	(94,NULL,'Volcano','Action / Thriller / Drama','English / Spanish / German',1.50,'After a seemingly minor earthquake one night in Los Angeles, a giant burst of lava is released from the La Brea Tar Pits, resulting in the birth of a new volcano under the city. City officials are reluctant to believe scientists who notice the early warning signs (the temperature of a lake rises 6 degrees in 12 hours) but they learn their lesson when lava begins to spill out into the streets and to destroy buildings and cars. Dedicated Emergency Management director Mike Roark rushes to the rescue, with help from a plucky seismologist',''),
	(95,NULL,'Waterworld','Action / Adventure / Drama / Sci-Fi / Thriller','English',2.15,'In a future where the polar ice caps have melted and most of Earth is underwater, a mutated mariner fights starvation and outlaw \"smokers,\" and reluctantly helps a woman and a young girl find dry land',''),
	(96,NULL,'Wild Wild West','Action / Western / Comedy / Sci-Fi','English',1.50,'Legless Southern inventor Dr. Arliss Loveless plans to rekindle the Civil War by assassinating President U.S. Grant. Only two men can stop him: gunfighter James West and master-of-disguise and inventor Artemus Gordon. The two must team up to thwart Loveless\' plans',''),
	(97,NULL,'Wing Commander','Action / Sci-Fi','English',1.40,'The descendants of the first ones to travel space are regarded as people of lesser worth. Half a millennium after the first ships launched in search of a better life, the Pilgrims still are discriminated. When the Kilrathi declare war against the human race, it is up to Christopher Blair, Pilgrim halfling, to help avoid complete annihilation. Since the Kilrathi managed to conquer a Navcom unit, they know the jump coordinates to Earth. And since the terran fleet is two hours further away from home than the Kilrathi fleet, the only hope of Mankind is to set trust in a Pilgrim, who can astrogate by feeling and does not need a Navcom unit - it\'s all genetics',''),
	(98,NULL,'Wolf','Drama / Horror / Romance / Thriller','English',2.00,'After publishing executive Will Randall is bitten by a wolf, his life begins to change. First his mood changes, and his sense of hearing and smell go into overdrive. Will has become a werewolf and he has an appetite for human blood. His newly found friend, Laura Alden wants to help, but she doesn\'t know what Will is yet. If Will\'s new problem wasn\'t enough to keep him occupied he must also contend with Stewart Swinton who is out to get his job',''),
	(99,NULL,'The X Files','Horror / Mystery / Sci-Fi / Thriller/ Thriller','English',2.00,'Two people from two worlds. FBI Agent Fox Mulder, a believer. FBI Agent Dana Scully, a Skeptic. Together they must solve the mysteries such as who, or what destroyed a Federal Building in Dallas, what killed 4 firemen and a child supposedly killed in the blast and more, but these mysteries were not placed by some insane terrorist, these were placed by our very own Government',''),
	(100,NULL,'X-Men','Action / Adventure / Sci-Fi / Thriller','English',1.40,'In a world where both Mutants and Humans fear each other Marie D\'Ancanto, better known as Rogue (Paquin) run away from home and hitches a ride with another mutant, known as Logan a.k.a Wolverine (Jackman). Charles Xavier (Stewart) who owns a school for young mutants, sends Storm (Berry) and Cyclops (Marsden) to bring them back before it is too late. Magneto (McKellen) who believes a war is approaching, has an evil plan in mind, and needs young Rogue to help him',''),
	(101,NULL,'X2','Action / Adventure / Sci-Fi / Thriller','English / German / Italian',2.15,'After the events on Liberty Island, everyone at Xavier\'s School for Gifted Youngsters are settling in. Magneto (McKellen) is locked up in a plastic cell, Rogue (Paquin) and Bobby Drake (Ashmore) have finally got together, and Wolverine (Jackman) has set off to find the origins of where he came from. But it wont stay quiet for long. After a mutant attack on the President (Smith), everyone starts to fear any type of mutant. William Stryker (Cox) who plans to stop all mutants, takes over the school, causing Wolverine and his team of mutants to go into hiding. Stryker has managed to capture Xavier (Stewart) and will use him to create another version of cerebro. Wolverine and the team must now team up with their enemy, Magneto to stop Stryker before it\'s too late',''),
	(102,NULL,'Astérix et Obélix contre César','Adventure / Comedy / Family / Fantasy','English/ French / German',1.50,'The well-known little village from the Asterix and Obelix-comic books is in trouble: It is the last place not controlled by Rome...',''),
	(103,NULL,'What Dreams May Come','Drama / Fantasy / Romance','English',2.00,'Chris Neilson dies to find himself in a heaven more amazing than he could have ever dreamed of. There is one thing missing: his wife. After he dies, his wife, Annie killed herself and went to hell. Chris decides to risk eternity in hades for the small chance that he will be able to bring her back to heaven',''),
	(104,NULL,'When a Man Loves a Woman','Drama / Romance','English / Thai',2.10,'An airline pilot and his wife are forced to face the consequences of her alcoholism when her addictions threaten her life and their daughter\'s safety. While the woman enters detox, her husband must face the truth of his enabling behavior',''),
	(105,NULL,'The Siege','Action / Crime / Drama / Thriller','English',2.00,'After the abduction by the US military of an Islamic religious leader, New York City becomes the target of escalating terrorist attacks. Anthony Hubbard, the head of the FBI\'s Counter-Intelligence Task Force in New York, teams up with CIA operative Elise Kraft to hunt down the terrorist cells responsible for the attacks. As the bombings continue, the US government responds by declaring martial law, sending US troops, led by Gen. Devereaux, into the streets of New York City',''),
	(106,NULL,'You\'ve Got Mail','Comedy / Romance','English',2.00,'The owner of a large bookstore chain starts putting the owner of a small local bookstore out of business. Meanwhile they have been corresponding over the internet without knowing who either of them are. They can\'t stand each other in person but over the internet they are very attracted. He finds out who she is but she doesn\'t know. He starts to like her more but she still hates him. He has to fix it',''),
	(107,NULL,'Mercury Rising','Action / Drama / Thriller','English',1.50,'The NSA has developed what they believe is an unbreakable code which they call MERCURY. Now they ran a test to see if anyone can decipher the code by putting it in a puzzle magazine. Now Simon Lynch, an autistic boy who has an affinity for puzzles sees it and deciphers it and calls the NSA. Concerned the men in charge call their boss Kudrow and inform of what happened. Kudrow worried what might happen if this gets out orders that Simon be terminated. The man he sends kills his parents but is unable to find Simon and leaves when the police arrive. The police call the FBI to send someone to take a report of Simon who is missing and the man they send Art Jeffries is not exactly in good standing with the FBI because of an incident that occurred recently and is also not exactly OK because of the incident. Art finds Simon, who was hiding and takes him to the hospital. While there, the assassin takes another try but Art saves Simon and they go on the run',''),
	(108,NULL,'End of Days','Action / Fantasy / Horror / Mystery / Thriller','English / Latin',2.00,'On December 28th, 1999, the citizens of New York City are getting ready for the turn of the millennium. However, the Devil decides to crash the party by coming to the city, inhabiting a man\'s body, and searching for his chosen bride, a 20-year-old woman named Christine York. [If he bears her child between 11:00 PM and midnight on New Year\'s Eve], the world will end, and the only hope lies within an atheist ex-cop named Jericho Cane, who no longer believes in God because of the murder of his wife and daughter',''),
	(109,NULL,'Fortress','Action / Sci-Fi','English',1.35,'In a futuristic USA, it\'s forbidden to give birth to more than one child for each woman. As usual, you can escape to Mexico to avoid the authorities in USA, which is exactly what John and Karen Brennick were trying to do when Karen is pregnant with her second child (their first child was born dead). When they think they have made it they are discovered and put to prison (for 31 years), a modern prison called the \"Fortress\" where the prisoners are controlled by lasers, neutron-cannons, cameras, mind-scanners and electronic pain-causing devices in their stomachs. With those odds, John still plans to escape with his wife',''),
	(110,NULL,'Ever After','Romance / Comedy / Drama / Fantasy','English',2.00,'If Cinderella was a true story, it would be very much like Ever After. Danielle D\'Barbarac, is the strong, fiery daughter of a dead nobleman. She works as a servant to her step mother, the Baroness D Gent. One day Danielle pretends to be a courtier to help a servant escape from being taken to the Americas. She captures the eye of the most unlikely person, the crowned prince of France! The two fall in love, but they are up against the ruthless Baroness D Gent, and her spoiled daughter, Marguerite who are determined to see that Margurite becomes Henry\'s bride. However with the servants, Danielle\'s kind step sister, Jacqueline, and Leonardo Da Vinci on Danielle\'s side, Danielle and Prince Henry\'s love can survive even though he is a prince and she is a servant girl',''),
	(111,NULL,'The Seventh Sign','Drama / Fantasy / Thriller','English',1.40,'Around the world, the signs of the apocalypse--as outlined in the Book of Revelation--seem to be coming to pass in the wake of a mysterious wanderer. Father Lucci, the Vatican Emissary assigned to investigate, dismisses the occurrences as natural, but Abby Quinn, a young American woman, has reason to fear they\'re real--and that the unfolding events may spell disaster for her unborn child',''),
	(112,NULL,'Message in a Bottle','Drama / Romance','English',2.15,'A divorced single mother finds a bottle on the shore whilst out jogging. Much taken with the sentiments of the message inside she uses the resources of the Chicago paper she works for to track down the sender. When she meets him an affection quickly forms between them, and his cantankerous father is also taken with her. But it is obvious something in the past is casting a terrible shadow',''),
	(113,NULL,'Dangerous Liaisons','Drama / Romance','English',2.00,'Set in France around 1760-1770. The Marquise de Merteuil needs a favour from her ex-lover, Vicomte de Valmont. One Marquise de Merteuil\'s ex-lover, Gercourt, is planning on marrying a young, virtuos, woman called Cecile de Volanges. The Marquise would like Valmont to seduce Cecile before her wedding day. Meanwhile Valmont has a conquest of his own in mind, Madame de Tourvel, a beautiful, married, and God fearing woman. The Marquise doesn\'t think that Valmont can do it, she tells him that if he can provide written proof of a sexual encounter with Madame de Tourvel, that she will offer him a reward, one last night with her. But Valmont will find himself falling in love with Mrs. de Tourvel, embrasing the deadly jealousy of the marquise de Merteuil',''),
	(114,NULL,'Swept from the Sea','Drama / Romance','English',2.00,'The film tells the story of Russian emigree and the only survivor from ship crash Yanko Goorall and servant Amy Foster in the end of 19th century. When Yanko enters a farm sick and hungry after the shipwreck, everyone is afraid of him, except for Amy, who is very kind and helps him. Soon he becomes like a son for Dr. James Kennedy and romance between Yanko and Amy follows',''),
	(115,NULL,'Enemy of the State','Action / Drama / Thriller','English',2.20,'Robert Clayton Dean is a successful labor lawyer based in Washington DC. He has a beautiful wife and adorable son with a nice house located in Georgetown. But things take a turn for the surreal, when a chance encounter with an old friend leaves him evidence of a politically-motivated murder. On the run from a treacherous NSA official and his men, he comes into contact with a former government operative and surveillance expert, who is his only way out',''),
	(116,NULL,'Any Given Sunday','Drama / Sport','English',2.00,'An aging football coach finds himself struggling with his personal and professional life while trying to hold his team together. A star quarterback has been knocked out of the game and a naive football player replaces him only to become exposed to the world of sports and become a danger to himself and to his players. Meanwhile, the coach finds himself constantly at battle with the team owner\'s money and power hungry daughter intent on moving the team out',''),
	(117,NULL,'Drop Zone','Action / Thriller','English',1.40,'U.S. Marshall Pete Nesbitt and his brother, Terry also a marshall is escorting a computer criminal Earl Leedy when all of a sudden a highjacking on the plane they are on occurs. Now Leedy and Terry are sucked out of the plane when Pete discharges his weapon and a hole in the plane is made. Nesbitt is blamed for the whole thing and is suspended. Now Terry\'s dead and Leedy, whose body hasn\'t been found is believed to be. But what they don\'t know is that Leedy is now with some people who want to use his computer skills. Pete doesn\'t believe that Leedy is dead and that the whole thing was to spring Leedy. So he turns to Jess Crossman, a skydiver, for help on who may have done this whole thing',''),
	(118,NULL,'Love\'s Labour\'s Lost','Romance / Comedy / Musical','English',1.33,'The King of Navarre and his three companions swear a very public oath to study together and to renounce women for three years. Their honour is immediately put to the test by the arrival of the Princess of France and her three lovely companions. It\'s love at first sight for all concerned followed by the men\'s highly entertaining but hopeless efforts to disguise their feelings',''),
	(119,NULL,'As Good as It Gets','Comedy / Drama / Romance','English',2.20,'New York City. Melvin Udall, a cranky, bigoted, obsessive-compulsive writer, finds his life turned upside down when neighboring gay artist Simon is hospitalized and his dog is entrusted to Melvin. In addition, Carol, the only waitress who will tolerate him, must leave work to care for her sick son, making it impossible for Melvin to eat breakfast',''),
	(120,NULL,'Saving Private Ryan','Action / Drama / War','English / French / German / Czech',2.50,'During WWII, Chief of Staff, General Marshall is informed that three of a woman\'s sons have been killed and that she\'s going to receive the notifications of their demise at the same time. And when he learns that a fourth son is still unaccounted for, the General decides to send a unit to find him and bring him back, despite being told that it\'s highly unlikely that he is still alive and the area that he was known to be at is very dangerous. So the unit consisting of 8 men are sent to find him but as stated it\'s very dangerous and one by one, each of them are being picked off. Will they find him and how many of them will still be alive',''),
	(121,NULL,'The Story of Us','Drama / Comedy / Romance','English / Italian',1.35,'Two jilted lovers spend fifteen years of marriage together, only to find that they might no longer love each other. In this time they have two children and go through the various (dramatic and comical) events that take place in an average marriage',''),
	(122,NULL,'The Preacher\'s Wife','Drama / Romance / Fantasy / Comedy','English',2.10,'Good natured Reverend Henry Biggs (Courtney B. Vance) finds that his marriage to choir mistress Julia (Whitney Houston) is flagging, due to his constant absence caring for the deprived neighbourhood they live in. On top of all this, his church is coming under threat from property developer Joe Hamilton (Gregory Hines). In desperation, Rev. Biggs prays to God for help - and help arrives in the form of an angel named Dudley (Denzel Washington). However, Dudley\'s arrival seems to cause even more trouble...','');

/*!40000 ALTER TABLE `film` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
